import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getPebbleVoice } from '../lib/pebbleVoice.js';

export default function TrainingPlanView() {
  const navigate = useNavigate();
  const [expandedDay, setExpandedDay] = useState(null);
  const [mentalScenarios, setMentalScenarios] = useState([]);

  useEffect(() => {
    getPebbleVoice().then(data => {
      if (data && data.mental_scenarios) {
        setMentalScenarios(data.mental_scenarios);
      }
    });
  }, []);

  if (expandedDay !== null) {
    const scenarioIndex = expandedDay - 1;
    const scenarioText = mentalScenarios[scenarioIndex] || 'Loading scenario...';
    
    return (
      <div className="card" style={{ maxWidth: '800px', margin: '0 auto' }}>
        <button className="secondary" onClick={() => setExpandedDay(null)} style={{ marginBottom: '20px' }}>← Back to Plan</button>
        
        <header style={{ marginBottom: '24px' }}>
          <h1 style={{ margin: 0, color: 'var(--accent)' }}>Day {expandedDay}: Mental Visualization</h1>
        </header>

        <h3 style={{ borderBottom: '1px solid var(--line)', paddingBottom: '12px', marginBottom: '16px' }}>Training Module</h3>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', marginBottom: '32px' }}>
          <div style={{ background: 'var(--panel-2)', padding: '16px', borderRadius: '12px', fontSize: '1rem', lineHeight: '1.6', color: 'var(--fg)' }}>
            {scenarioText}
          </div>
        </div>

        <div style={{ display: 'flex', gap: '16px' }}>
          <button className="primary" style={{ flex: 1, background: 'var(--accent)', color: '#fff', border: 'none', padding: '12px', borderRadius: '999px', fontWeight: 600, cursor: 'pointer' }} onClick={() => navigate('/shoot')}>
            Start Timer & Log Session
          </button>
          <button className="secondary" style={{ flex: 1, padding: '12px', borderRadius: '999px', fontWeight: 600, cursor: 'pointer' }} onClick={() => setExpandedDay(null)}>
            Mark Day as Complete
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="card" style={{ maxWidth: '1000px', margin: '0 auto' }}>
      <header style={{ marginBottom: '32px', textAlign: 'center' }}>
        <h1 style={{ margin: 0, color: 'var(--good)' }}>Your Mental Training Plan</h1>
        <p style={{ color: 'var(--muted)', margin: '8px 0 0' }}>Advanced visualization scenarios generated by your Pebble Coach.</p>
      </header>

      <h3 style={{ marginBottom: '16px' }}>Available Scenarios</h3>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px' }}>
        
        {mentalScenarios.length > 0 ? mentalScenarios.map((scenario, index) => {
          const dayNum = index + 1;
          const previewText = scenario.substring(0, 80) + '...';
          return (
            <div key={index} style={{ background: 'var(--panel)', border: '2px solid var(--accent)', borderRadius: '12px', padding: '20px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }}>
                <span style={{ fontWeight: 600 }}>Scenario {dayNum}</span>
                <span style={{ fontSize: '0.8rem', background: 'var(--panel-2)', color: 'var(--text)', padding: '2px 8px', borderRadius: '999px' }}>Mental</span>
              </div>
              <div style={{ color: 'var(--text)', fontSize: '0.9rem', lineHeight: '1.5', marginBottom: '16px' }}>
                {previewText}
              </div>
              <button style={{ width: '100%', marginTop: 'auto' }} onClick={() => setExpandedDay(dayNum)}>Read Scenario</button>
            </div>
          );
        }) : (
          <div style={{ color: 'var(--muted)', gridColumn: '1 / -1', textAlign: 'center', padding: '40px' }}>
            No mental scenarios available yet. They will be generated tomorrow!
          </div>
        )}
      </div>
    </div>
  );
}
