import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getPebbleVoice } from '../lib/pebbleVoice.js';
import { useSession } from '../context/SessionContext.jsx';

export default function TrainingPlanView() {
  const navigate = useNavigate();
  const { startSession } = useSession();
  const [mentalScenarios, setMentalScenarios] = useState([]);

  useEffect(() => {
    getPebbleVoice().then(data => {
      if (data && data.mental_scenarios) {
        setMentalScenarios(data.mental_scenarios);
      }
    });
  }, []);

  const scenarioText = mentalScenarios[0];

  const handleStartMental = () => {
    startSession('mental', 'shot');
    navigate('/session');
  };

  return (
    <div className="card" style={{ maxWidth: '800px', margin: '0 auto' }}>
      <header style={{ marginBottom: '32px', textAlign: 'center' }}>
        <h1 style={{ margin: 0, color: 'var(--accent)' }}>Your Mental Training Plan</h1>
        <p style={{ color: 'var(--muted)', margin: '8px 0 0' }}>Advanced visualization scenarios generated by your Pebble Coach.</p>
      </header>

      {scenarioText ? (
        <div style={{ background: 'var(--panel)', border: '2px solid var(--accent)', borderRadius: '12px', padding: '24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
            <span style={{ fontWeight: 600, fontSize: '1.2rem', color: 'var(--fg)' }}>Today's Scenario</span>
            <span style={{ fontSize: '0.8rem', background: 'var(--panel-2)', color: 'var(--text)', padding: '4px 12px', borderRadius: '999px' }}>Mental</span>
          </div>
          
          <div style={{ background: 'var(--bg-subtle)', padding: '20px', borderRadius: '12px', fontSize: '1.05rem', lineHeight: '1.6', color: 'var(--fg)', marginBottom: '24px' }}>
            {scenarioText}
          </div>

          <div style={{ display: 'flex', gap: '16px' }}>
            <button className="primary" style={{ flex: 1, background: 'var(--accent)', color: '#fff', border: 'none', padding: '14px', borderRadius: '999px', fontWeight: 600, cursor: 'pointer', fontSize: '1rem' }} onClick={handleStartMental}>
              Start Mental Training
            </button>
          </div>
        </div>
      ) : (
        <div style={{ color: 'var(--muted)', textAlign: 'center', padding: '40px' }}>
          No mental scenarios available yet. They will be generated soon.
        </div>
      )}
    </div>
  );
}
